### ISSUE TITLE
Implement a menu for activating additional tests

### ISSUE THREAD

**Issue by skiselev** [brendanalford/zx-diagnostics#16]
Currently the method for activating additional tests (e.g. ULA, Keyboard, Soak test) is not obvious. It would be nice to add a menu that would allow activating these tests, or at least have a help screen showing the hot keys for activating these tests.

**Comment by brendanalford** [comment]
This seems sensible, I'll look at how best to achieve this in the next release.

**Comment by brendanalford** [comment]
Added hot key display on startup with commit 084c6cd.

**Comment by brendanalford** [comment]
![capture](https://cloud.githubusercontent.com/assets/8959844/13531472/a6eda862-e21e-11e5-9aa1-0906833ba420.JPG)

Example of startup screen.
