### ISSUE TITLE
How to Build (prerequisites)

### ISSUE THREAD

**Issue by eprive** [brendanalford/zx-diagnostics#22]
Trying to build from the sources, and missing some tools.

The "how to build" states : all that needs to be done is to run the build.bat 
But there is probably a little more before the build will succeed.

Of course I did copy sjasmplus.exe to a folder which is in my path.
A few errors appear when the build.bat is run, namely:
- git (I did not not have a local git yet);
- installed git, and I get further git related errors: "fatal, not a git related repository"
and the script runs further and reports :

"************************
Building Diagboard stuff
************************
Building Diagboard detection routines...
SjASMPlus Z80 Cross-Assembler v1.07 RC7 (build 02-04-2008)
Pass 1 complete (0 errors)
Pass 2 complete (0 errors)
Pass 3 complete
Errors: 0, warnings: 0, compiled: 1292 lines, work time: 0.016 seconds
*****************
Building Main ROM
*****************

Building Test ROM...
SjASMPlus Z80 Cross-Assembler v1.07 RC7 (build 02-04-2008)
testrom.asm(49): error: [LUA] attempt to concatenate global 'branch' (a nil value)
Pass 1 complete (1 errors)
testrom.asm(49): error: [LUA] attempt to concatenate global 'branch' (a nil value)
Pass 2 complete (2 errors)
testrom.asm(49): error: [LUA] attempt to concatenate global 'branch' (a nil value)
testrom.asm(88): error: Label not found: BUILD_TIMESTAMP
testrom.asm(92): error: Label not found: GIT_BRANCH
testrom.asm(96): error: Label not found: GIT_COMMIT
testrom.asm(100): error: Label not found: HOSTNAME
Pass 3 complete
Errors: 7, warnings: 0, compiled: 12288 lines, work time: 0.094 seconds
Aborting main build." 

And are there more requirements such as bin2tap, ... ?

**Comment by brendanalford** [comment]
In order to successfully build zx-diagnostics, you do need to clone the repository, as the LUA scripting depends on being able to pull branch and commit information, as you've noticed. You also need the bin2tap executable, which isn't included in this source (I may need to write my own implementation so it can be bundled as part of this distribution).

I'll separate this into a new 'How to Build' page in the future. Thanks for the report!

**Comment by eprive** [comment]
It would be nice to have a version without any git related bits. Assemble to a rom file only.

**Comment by brendanalford** [comment]
I've added Linux scripts in the v0.37-release branch, and the builds no longer fail if git is not present or the current directory is not a git repo.

**Comment by brendanalford** [comment]
@eprive - Let me know if the build scripts in v0.37 work for you, if so this issue can be closed.

**Comment by brendanalford** [comment]
No response in over 4 months, closing. @eprive, please feel free to reopen if needed.
