### ISSUE TITLE
Hold a key to reset keyboard test

### ISSUE THREAD

**Issue by jcnventura** [brendanalford/zx-diagnostics#30]
Related to #27, but maybe easier to implement, would it be possible to reset the keyboard test by holding a given key (delete?) for a long time. Nowadays, I press the NMI button to get this effect, as when testing the extended keyboards, you end up marking some keys as tested when they were not, and it's not easy to see anymore what was detected.

Resetting the test would also simplify testing the extended keyboard, as it would be simple to see that both keys necessary for the equivalent keypress were activated.

**Comment by brendanalford** [comment]
This sounds reasonable, so I propose that holding the space bar/key down for more than a second would reset the keyboard test, the message displayed would be something like 'Press all keys to test, hold SPACE to reset, BREAK to exit'.

**Comment by brendanalford** [comment]
Apologies for the delay, this facility has been added to the v0.38 release branch (commit aac1076)
