### ISSUE TITLE
PCB files

### ISSUE THREAD

**Issue by DFL1973** [brendanalford/zx-diagnostics#33]
Hi, thanks for sharing. What program is used to generate the Gerbers? I tried to open the files in the "hardware" folder with Kicad, Altium, and Eagle, but none of them seems to work.

**Comment by brendanalford** [comment]
They should be KiCad compatible, but they are at least 12 years old at this point and should be considered deprecated. They will be removed in the next release as they have been superseded by Steve Smith's enhancement at [Project Speccy](https://projectspeccy.com/2019/05/20/testing-testing/)

**Comment by ZXGuesser** [comment]
The hardware files are for `gschem` and `pcb` from www.geda-project.org (which seem to be down right now)

**Comment by brendanalford** [comment]
I stand corrected - point about deprecation still stands though :)

**Comment by DFL1973** [comment]
> They should be KiCad compatible, but they are at least 12 years old at this point and should be considered deprecated. They will be removed in the next release as they have been superseded by Steve Smith's enhancement at [Project Speccy](https://projectspeccy.com/2019/05/20/testing-testing/)

Is Steve Smith layout available? I can´t find there
